### ISSUE TITLE
[QUESTION] Difference between delay and departureDelay/arrivalDelay for Stops

### ISSUE THREAD

**Issue by DylanVanAssche** [iRail/iRail-docs#8]
I was wondering what the difference is between the 'delay' keyword and the 'departureDelay' and 'arrivalDelay' keywords for a Stop object? It's the only place where there's a difference, the rest of the API uses 'delay' only.

If departureDelay = delay then I can safely ignore that keyword.
The same for the 'time' keyword and the 'scheduledDepartureTime' and 'scheduledArrivalTime' keywords.

Thanks!

**Comment by Bertware** [comment]
For a train we have data about the departure and about the arrival. A train can arrive at 12:00 with 2 minutes delay and leave at 12:01 with 3 minutes delay. 
Delay and time are here included for backwards compatibility, and are the same as departureDelay and departureTime (You'll find more duplicate data in API responses if you look for it, it's always for backwards compatibility).

**Comment by DylanVanAssche** [comment]
Thanks for your reply :)
I just wanted to be sure in order to avoid that I need to change my data models in the future.
